name: api100ms_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hmssdk_flutter: 0.6.0
  http: 0.13.4
  logger: 1.1.0
  permission_handler: 9.2.0
  provider: 6.0.2
  uuid: 3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter:
  uses-material-design: true